# Path, where built zip packages will be saved
DESTINATION_ABS_PATH: '/tmp'

# Destination catalog name in 'DESTINATION_ABS_PATH' path
TARGET_CATALOG_NAME: 'PACKAGES'

# Release tag for TrustedAnalytics projects, it will be applied for all TA apps, it can be overwritten in cloud_apps.yml file
RELEASE_TAG:

# Version for atk projects
ATK_VERSION: 'latest'
